server:
  session:

  servlet:
    context-path: /user
    session:
      cookie:
        max-age:
      timeout:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/downloadbase?characterEncoding=utf8&useSSL=true

    username: root
    password: 123456
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  jpa:
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: update
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
    encoding: UTF-8
    resources:
      static-locations: ["/templates/","/resources/","/static/", "/css/"]
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
#logging:
#  path: E:\IDEA projects\spring-boot-chapter\DownloadTool\log



